spring:
  rabbitmq:
    host: 49.234.21.180
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
    listener:
      simple:
        #消息的手动确认
        acknowledge-mode: manual